### ISSUE TITLE
import pybel_jupyter fails

### ISSUE THREAD

**Issue by djinnome** [pybel/pybel-jupyter#5]
Hi folks,

It seems that the latest versions of `pybel_jupyter` and `pybel` are out of sync, because `pybel.io` no longer has the `to_jsons` function.  Which version of pybel should I downgrade to so that this will work?

When I try to run the canonical example, 
```python
from pybel.examples import sialic_acid_graph
import pybel_jupyter 
```
I get the following error:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-1544693f4025> in <module>
      1 from pybel.examples import sialic_acid_graph
----> 2 import pybel_jupyter

~/Projects/Proposals/MARS/Pathogenesis/pybel-jupyter/src/pybel_jupyter/__init__.py in <module>
      3 """A PyBEL extension for Jupyter notebooks."""
      4 
----> 5 from .inline import to_jupyter, to_jupyter_str  # noqa: F401
      6 from .utils import get_version  # noqa: F401
      7 from .visualization import to_html, to_html_file, to_html_path  # noqa: F401

~/Projects/Proposals/MARS/Pathogenesis/pybel-jupyter/src/pybel_jupyter/inline.py in <module>
      9 
     10 from pybel import BELGraph
---> 11 from pybel.io import to_jsons
     12 from .constants import DEFAULT_COLOR_MAP
     13 from .utils import render_template

ImportError: cannot import name 'to_jsons' from 'pybel.io' (/Users/zuck016/Projects/Proposals/MARS/Pathogenesis/pybel/src/pybel/io/__init__.py)
```

**Comment by cthoyt** [comment]
Hi @djinnome, you're right, things are a bit out of sync at the moment if you're installing from GitHub. Could you tell me how you've installed everything?

Either way I'll be releasing PyBEL 14 and updating `pybel_tools`, `pybel_jupyter`, `bel_repository`, and `bel_commons` to reflect that. Each already has a branch where those updates are taking place that you could check out

**Comment by djinnome** [comment]
Hi @cthoyt I am just installing from pip right now:
```
!pip install pybel
!pip install pybel-jupyter
from pybel.examples import sialic_acid_graph as sag
import pybel_jupyter

**Comment by cthoyt** [comment]
Hi @djinnome, sorry this fell through the cracks! I just made a fix in pybel/pybel@d6e7e619 and will be releasing a new version of pybel and pybel-jupyter momentarily.

**Comment by cthoyt** [comment]
The code has been updated in dee415d. Please upgrade both `pybel` to v0.14.7 and `pybel-jupyter` to v0.3.0 with

```bash
pip install --upgrade pybel
pip install --upgrade pybel-jupyter
```

and re-open the issue if there are any remaining problems!

**Comment by djinnome** [comment]
Hi @cthoyt 

I upgraded pybel  and pybel_jupyter, and I am still getting the javascript error.  I am using Jupyter Lab Version 2.1.0. 

```python
!pip install --upgrade pybel==0.14.7
!pip install --upgrade pybel_jupyter==0.3.0
from pybel.examples import sialic_acid_graph as sag
import pybel_jupyter
```

```
Javascript Error: require is not defined
```

Interestingly, when I try it in Jupyter notebook, it works fine.  I wonder if it is related to the following issue: https://github.com/vega/ipyvega/issues/103  or this: https://github.com/jupyter-widgets/ipywidgets/issues/2379

Anyway, I have a workaround now, so this is less of a priority for me.  

Thanks for the superfast response!  PyBEL is awesome.



Sincerely

**Comment by cthoyt** [comment]
@djinnome I've never used Jupyter Lab. Unfortunately, I already feel like this entire Jupyter plugin was hacky at its core, so I'm sure what works is only by accident 😆 

I saw what's going on in your other repos at https://github.com/covid-19-causal-reasoning, too. I would love to chat about that once your work starts to mature
